### ISSUE TITLE
Plug-in Switch Mini TZWP102 - Not reconecting after power outage

### ISSUE THREAD

**Issue by flundberg81** [yhaugom/com.telldus#25]
Cant get my mini-switch to re-connect after a power outage

**Comment by yhaugom** [comment]
@flundberg81 please reach out to [support@athom.com](mailto:support@athom.com)
This should not be related to this app. I have testet now with a plug just to be certain. 
It could however be related to range from Homey. 
There is nothing in the Telldus app that has anything to do with the reconnection of the plug. It is just a standard Z-wave app based on Athom standard templates. If it is a coding bug, it should be a core issue.
I have heard that secure inclusion can make the plug more unreliable, but since it is not possible to give the user the option to choose secure or non-secure inclusion, I do not want to switch over to non-secure inclusion for everyone.
Athom should, in my opinion, make it possible for me to give the users the option to choose secure or non-secure inclusion.
Telldus does not give the option on the device itself, as Aeotec does (on aeotec sensor 6 you can choose by pushing inclusion button once or three times).
Only thing you could do is to try to clone the repository and add the line ""includeSecure": false,"
under TZWP-102 in the app.json file, and then install the app trough CLI from a computer.
If you do this it is on your own risk. You can find information on how to do this [here](http://developer.athom.com/docs/apps/tutorial-Getting%20Started.html)
Sorry for your troubles.
