### ISSUE TITLE
When adding a Miniplug device the installationinformation is wrong.

### ISSUE THREAD

**Issue by sepatneu** [yhaugom/com.telldus#26]
When adding a Miniplug device the installationinformation is wrong. 
Its refering to removing device. See attatched pic. 

![063E23B4-67D3-40D1-9385-A1D235704D86](https://user-images.githubusercontent.com/50592756/102119825-048c4f80-3e42-11eb-8b67-f38fdd4d4ca7.png)

**Comment by yhaugom** [comment]
This is because Athom changed the way a device is included. They first do a removal before including the device to make sure it is completely removed. 
I think it is due to the problem that occurs when a device including partially fails. Then you previously had to remove the device manually before re-including.
I will try to find a more generic description, but this description is actually not incorrect... technically.

**Comment by BolmsoAnders** [comment]
When I try to add the TZWP-102 it looks like the removal works and after "clicking" 3 times again the adding seems to start correct but it end with a time out and a fault message. I have tryed with two different devices with the sam result.

**Comment by dvlin** [comment]
Same issue as @BolmsoAnders

**Comment by yhaugom** [comment]
Updated in last version.
